apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d
  labels:
    run: l5d
data:
  l5d.config.yaml: |-
    routers:
    - protocol: http
      servers:
      - ip: 0.0.0.0
        port: 80
      dstPrefix: /host
      dtab: |-
        /route => /env/stephpr ;
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/n4d.kube-system/4100
        namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: l5d
  labels:
    run: l5d
spec:
  replicas: 1
  selector:
    matchLabels:
      run: l5d
  template:
    metadata:
      labels:
        run: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: l5d
      containers:
      - name: l5d
        image: buoyantio/linkerd:0.9.1
        volumeMounts:
        - name: l5d-config
          mountPath: /io.buoyant/linkerd/config
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 9990
        args:
        - /io.buoyant/linkerd/config/l5d.config.yaml
        readinessProbe:
          tcpSocket:
            port: 9990
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
  labels:
    run: l5d
spec:
  selector:
    run: l5d
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: admin
    port: 9990