apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d
  labels:
    run: l5d
data:
  entrypoint.sh: |-
    mkdir -p $(dirname $2)
    sed \
      -e s/'$(POD_NAMESPACE)'/$POD_NAMESPACE/g \
      $(dirname $0)/l5d.config.yaml.tmpl > $2
    exec "$@"
  l5d.config.yaml.tmpl: |-
    routers:
    - protocol: http
      servers:
      - ip: 0.0.0.0
        port: 80
      dstPrefix: /host
      dtab: |-
        /route => /env/$(POD_NAMESPACE) ;
        /host => /$/io.buoyant.http.subdomainOfPfx/$(POD_NAMESPACE).svc.cluster.local/host ;
        /host => /$/io.buoyant.http.subdomainOfPfx/$(POD_NAMESPACE).svc/host ;
        /host => /$/io.buoyant.http.subdomainOfPfx/$(POD_NAMESPACE)/host ;
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/n4d.kube-system/4100
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: l5d
  labels:
    run: l5d
spec:
  replicas: 1
  selector:
    matchLabels:
      run: l5d
  template:
    metadata:
      labels:
        run: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: l5d
      containers:
      - name: l5d
        image: buoyantio/linkerd:0.9.1
        volumeMounts:
        - name: l5d-config
          mountPath: /l5d-config
          readOnly: true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 9990
        command:
        - /bin/sh
        - /l5d-config/entrypoint.sh
        - /io.buoyant/linkerd/0.9.1/bundle-exec
        args:
        - /io.buoyant/linkerd/config/l5d.config.yaml
        readinessProbe:
          tcpSocket:
            port: 9990
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
  labels:
    run: l5d
spec:
  selector:
    run: l5d
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: admin
    port: 9990
