apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
data:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
    spec:
      volumes:
      - name: nginx-ingress-controller-config
        configMap:
          name: nginx-ingress-controller
      containers:
      - name: nginx-ingress-controller
        image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          hostPort: 80
          containerPort: 80
        - name: https
          hostPort: 443
          containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: 10254
            path: /healthz
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 10254
            path: /healthz
          initialDelaySeconds: 10
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
spec:
  selector:
    k8s-app: nginx-ingress-controller
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
